apiVersion: v1
kind: Service
metadata:
  name: {{ include "estafette-ci.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "estafette-ci.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
