apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
spec:
  minReplicas: {{ .Values.pdb.minReplicas }}
  maxReplicas: {{ .Values.pdb.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "estafette-ci-api.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.pdb.targetCPUUtilizationPercentage }}